name: NexusHealing
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: Nexus Healing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000002'
    - '#fefefe'
    - '#5c2a5b'
    - '#b98aaa'
    - '#e0b4cf'
  brandStrength: 0.1875
  lightness: 0.3125
  saturation: 0.3125
  rhythmicContrast: 0
purpose: []
